### ISSUE TITLE
the armor became two.

### ISSUE THREAD

**Issue by excaliburkim** [Rapha149/ArmorStandEditor#1]
Thanks for making a great program.
One of the best plugin programs I've ever used.
However, this time there is a bug that one of our users found.
He put his armor on the armor stand and put it in and out of the inventory repeatedly, but then canceled it and found that the armor became two.
It's not easy to implement because it appears very rarely, but it does.
Please confirm. I just stopped using the plugin because of this. All of our users are waiting for the update.
thank you :)

**Comment by Rapha149** [comment]
Which server software are you using? And on which version?
And could you ask the user how fast he switched the item? Like, spamming, 1 sec, 2 sec ...
I will try to resolve it as fast as possible, but I don't know how hard the problem will be to solve so I can't give you an estimated time.

**Comment by excaliburkim** [comment]
Server Version: git-Purpur-1858 (MC: 1.19.2)
ArmorStandEditor: 1.3

Users say they clicked and dragged as fast as they could to find the bug.

**Comment by Rapha149** [comment]
can you ask the user what exactly he did?
Like, what do you mean by "but then canceled it" and where did he drag the item?

**Comment by Rapha149** [comment]
btw, for now you could disable the feature to replace equipment in the inventory so that you can still use the plugin but the bug won't be able to occur
you can do this in the config very easily

**Comment by Rapha149** [comment]
> can you ask the user what exactly he did? Like, what do you mean by "but then canceled it" and where did he drag the item?

Ok, I don't need this anymore, because I think I have a solution even though I can't reproduce the bug. The system with the synchronization between inventory and armor stand always was prone to errors so I will just remove that. The armor items will only be applied once the user closes the inventory. That should fix this bug.
I think I should be able to finish it tomorrow but it may take until Friday.

**Comment by excaliburkim** [comment]
Thank you for your help.
Always be happy!

**Comment by Rapha149** [comment]
The update is published on Spigot :)

**Comment by excaliburkim** [comment]
Thank you!!! :)
