### ISSUE TITLE
Bug report: ArmorStandEditor 1.4

### ISSUE THREAD

**Issue by excaliburkim** [Rapha149/ArmorStandEditor#2]
ArmorStandEditor 1.4

When I use the [Lock] function, all equipment disappears.

**Comment by Rapha149** [comment]
I will look into it.

**Comment by Rapha149** [comment]
I can't reproduce the bug right now. Could you please explain in detail what you did exactly?
For example: did the armor stand wore the equipment when you interacted with him or did you put it on him?

Also: do you mean the `Private` feature or the `Lock Slots` feature?

**Comment by excaliburkim** [comment]
1. Equip one or several items on the armor stand.
2. If I press the [Lock(Shulker Shell)] button, all items disappear.
3. Disappeared items cannot be recovered.

**Comment by Rapha149** [comment]
Does this happen every time? Because I can't seem to reproduce the bug. You're still on Purpur 1.19.2, right?

**Comment by excaliburkim** [comment]
![image](https://user-images.githubusercontent.com/41064236/224455498-00a60cc8-1f53-41e3-a922-28b61f536771.png)
Right! :)

**Comment by Rapha149** [comment]
Does the bug happen every time?

**Comment by excaliburkim** [comment]
Yes, it happens every time.

**Comment by Rapha149** [comment]
Ok, I know now why I couldn't reproduce the bug. I already fixed it (I don't know how) in a newer version of the plugin that I am currently programming and that is not yet released. So you just have to wait for the next update, I think I will be able to upload it tomorrow. I will also notify you here :)

**Comment by excaliburkim** [comment]
I am impressed with your quick response. :)
You are a wonderful developer.

**Comment by Rapha149** [comment]
Thanks!
The update is published.

**Comment by excaliburkim** [comment]
It's perfect.
Thank you very much!
Happy development!
