### ISSUE TITLE
Update the plugin to 1.20.6

### ISSUE THREAD

**Issue by Wamens** [Rapha149/ArmorStandEditor#3]
### Is your feature request related to a problem?

```bash
Would like to see this plugin updated to 1.20.6
```

### What solution would you like?

This plugin is great and would like to be see it updated

### Describe alternatives you've considered

N/A

**Comment by Rapha149** [comment]
I've been working on that already, unfortunately I can't update the plugin until one of my dependencies updates as well: https://github.com/TriumphTeam/triumph-gui/pull/112
Therefore I also can't give you a time estimate. As soon as the dependency is updated I can test and update my plugin.

**Comment by Rapha149** [comment]
The dependency was updated today, so I was able to update the plugin. The new version is online on Spigot.
