### ISSUE TITLE
[Bug] Pixel remains in the armorstand

### ISSUE THREAD

**Issue by Savranchuk** [Rapha149/ArmorStandEditor#6]
### Plugin version

1.5.7

### Server software and version

purpur 1.20.1

### Steps to reproduce

```bash
The armorstand plugin does not have a name reset function. If the player renames it to empty text, an empty field of one pixel is created. Logically, the text reset function should be performed.

Open the Armorstand menu
I open the second page and click on the tag (Performs the rename function)
The menu opens in the anvil and I remove all the text
As a result, one pixel of empty text appears, although logically there should be nothing
```

### Expected behaviour

I expect that after I remove all the text and save this action, there will be no text or the text will be reset

### What is actually happening?

If you break the stand, it doesn't help to remove the pixel. I would like to improve it somehow

**Comment by Rapha149** [comment]
Is this still the case when you remove the name using the recommended way by right-clicking the name tag?
(Check the lore of that item, it says left click to change the name and right click to remove it)

**Comment by Savranchuk** [comment]
Yes. works. The text was indicated, but surprisingly I did not read it. I apologize.

**Comment by Rapha149** [comment]
No problem.
