### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by Savranchuk** [Rapha149/ArmorStandEditor#8]
### What solution would you like?

Hello. It is possible to add a function to the ArmorStandEditor plugin so that it is impossible to place mobs on a stand. Players easily move them and spoil the vanilla gameplay

### Describe alternatives you've considered

Adding to the plugin config:

mob-set-armor: true/false - allow or disable the ability of mobs to sit on a stand

**Comment by Rapha149** [comment]
You can disable all features of this plugin or set a permission players have to have in order to use that feature in the config file.
![grafik](https://github.com/user-attachments/assets/917606ef-af29-4ac5-9fa3-953c7a30e7a5)

**Comment by Savranchuk** [comment]
Does this function only work on server players or on animals as well?

**Comment by Rapha149** [comment]
By default, this feature is only available for mobs, not for players. If you set `players` to `true` players can also be selected as passengers. If you set `enabled` to `false`, the feature will be disabled entirely, for player and mob passengers. If you set a permission like `armorstands.vehicle` only players that have that permission will be able to use the feature.

**Comment by Savranchuk** [comment]
Thank you very much for your quick response! Have a nice day!

**Comment by Rapha149** [comment]
You're welcome!
